# config/traefik.yml
api:
  dashboard: true  # 开启 dashboard
  debug: true      # 开启 debug 模式（可选，会显示更多信息）

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":6183"
  astrbot-entry:
    address: ":6184"
  napcat-entry:
    address: ":6098"

# 添加一个专门给 API 用的入口点（可选）
  traefik-api:
    address: ":443"  # API 和 dashboard 的入口

providers:
  file:
    filename: /etc/traefik/dynamic/dynamic.yml
    watch: true

# 开启访问日志
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 100
