# config/traefik.yml
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  # 新增两个端口分别对应两个服务
  astrbot-entry:
    address: ":6184"  # Astrbot 用 6184 端口
  napcat-entry:
    address: ":6098"  # Napcat 用 6098 端口
